# Generated by Django 6.0.1 on 2026-01-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
